// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RenoSystem.ENTITIES;


internal partial class RenosContext : DbContext
{
    public RenosContext(DbContextOptions<RenosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<DbVersion> DbVersions { get; set; }

    public virtual DbSet<Job> Jobs { get; set; }

    public virtual DbSet<Labour> Labours { get; set; }

    public virtual DbSet<Supply> Supplies { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("PK_Clients_ClientId");

            entity.Property(e => e.Phone).IsFixedLength();
            entity.Property(e => e.PostalCode).IsFixedLength();
            entity.Property(e => e.Province).IsFixedLength();
        });

        modelBuilder.Entity<DbVersion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_DbVersion_Id");
        });

        modelBuilder.Entity<Job>(entity =>
        {
            entity.HasKey(e => e.JobId).HasName("PK_Jobs_JobId");

            entity.HasOne(d => d.Client).WithMany(p => p.Jobs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JobsClients_ClientId");
        });

        modelBuilder.Entity<Labour>(entity =>
        {
            entity.HasKey(e => e.LabourId).HasName("PK_Labours_LabourId");

            entity.HasOne(d => d.Job).WithMany(p => p.Labours)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LaboursJobs_JobId");
        });

        modelBuilder.Entity<Supply>(entity =>
        {
            entity.HasKey(e => e.SupplyId).HasName("PK_Supplies_SupplyId");

            entity.HasOne(d => d.Job).WithMany(p => p.Supplies)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SuppliesJobs_JobId");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}