using Microsoft.EntityFrameworkCore.ChangeTracking;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

#region Additional Namespaces
using WestWindSystem.DAL;
using WestWindSystem.Entities;
#endregion

namespace WestWindSystem.BLL
{
    public class ProductServices
    {
        #region setup of the context connection variable and class constructor
        private readonly WestWindContext _context;

        internal ProductServices(WestWindContext registeredcontext)
        {
            _context = registeredcontext;
        }
        #endregion

        #region Queries
        public List<Product> Product_GetByCategoryID(int categoryid)
        {
            //IEnumerable<Product>info = _context.Products
            //                            .Where(x => x.CategoryID == categoryid);
            //return info.OrderBy(x => x.ProductName).ToList();

            return _context.Products
                           .Where(x => x.CategoryID == categoryid)
                           .OrderBy(x => x.ProductName)
                           .ToList();
        }

        public Product Product_GetByProductID(int productid)
        {
            return _context.Products.FirstOrDefault(x => x.ProductID == productid);
        }
        #endregion

        #region CRUD (Add, Update and Delete)

        public int Product_Add(Product item)
        {

            //Adding a record to your database may require additional validation that was not
            //  done on the front end
            //Such validation could be
            //  was data actually passed to the method
            //  the pkey may not be created on the database, it is user supplied
            //      the pkey value supplied should be tested to see if it already exists
            //  there could be a set of business rules that envolve checking data against
            //      existing data on the database that is not part of the record being added

            //do any validation needed within the service

            //was data passed
            if (item == null) 
                throw new ArgumentNullException("Product information not submitted");

            //does the pkey exist?
            //product has a pkey of IDENTITY
            //there is no need to check to see if the pkey already exists since the
            //      primary key will be generated by the database

            //are there any other business rules to check
            //YOU MAY NOT HAVE ANY OTHER BUSINESS RULES TO CHECK!!!!!!!!!!!!!!!!!!!
            //An example of business rules for this demo could be that the product
            //  a) is not from the same supplier
            //  b) with the same product name
            //  c) having the same quantity per unit
            bool exist = false;
            exist = _context.Products
                        .Any(x => x.SupplierID == item.SupplierID
                                && x.ProductName.Equals(item.ProductName)
                                && x.QuantityPerUnit == item.QuantityPerUnit);
            if (exist)
                throw new ArgumentException($"{item.ProductName} from " +
                            $"{item.Supplier.CompanyName} of size " +
                            $"{item.QuantityPerUnit} already on file.");

            //after all business rules have been passed, you can assume the 
            //  data is good to be placed on the database

            //if your field is an IDENTITY key then override any value in the field 
            //  to zero
            //prevents an IDENTITY_INSERT flag problem from occuring
            item.ProductID = 0;

            //there is two steps to complete the process of adding your data to the database
            // a) Staging
            // b) Commit

            //Staging
            //EntityFramework sets up all db processing in local memory first
            //what is needed for staging
            // a) know the DbSet : Products
            // b) know the action : Add
            // c) know the instance of the DbSet to use: item

            //IMPORTANT: the data is in LOCAL MEMORY
            //           the data is NOT!!! yet been sent to the database
            //THEREFORE: at this time, there is NO!!!!! IDENTITY primary key value
            //              on this instance (except for the default of the datatype)
            //UNLESS: you have place a value in the NON_IDENTITY key field(s)
            _context.Products.Add(item);

            //Commit
            // this sends the ALL staged data in local memory to the database for processing

            //ANY annotation validation in your entity is executed to validate the data
            //  going to the database
            //if there is a validation problem then an exception is thrown and processing of
            //  the commit is terminated (transaction RollBack)
            _context.SaveChanges(); //if successful, data is committed

            //AFTER the successful commit to the database, your new product id
            //  primary key value is available to you via the item.ProductID
            //Optionally, you could return this value to the calling process


            return item.ProductID;
        }

        public int Product_Update(Product item)
        {
            //was data passed
            if (item == null)
                throw new ArgumentNullException("Product information not submitted");

            //does the pkey exist?
            //check via a readonly query that your record target actually exists
            //on the update, this means a simple Any() test
            if(!_context.Products.Any(x => x.ProductID == item.ProductID))
                throw new ArgumentException($"{item.ProductName}  of size " +
                           $"{item.QuantityPerUnit} does not exist on file. Please check for product again.");

            //are there any other business rules to check
            //YOU MAY NOT HAVE ANY OTHER BUSINESS RULES TO CHECK!!!!!!!!!!!!!!!!!!!
            //An example of business rules for this demo could be that the product
            //  a) is not from the same supplier
            //  b) with the same product name
            //  c) having the same quantity per unit
            // AND for update
            //  d) is NOT the current product (all other products)
            bool exist = false;
            exist = _context.Products
                        .Any(x => x.SupplierID == item.SupplierID
                                && x.ProductName.Equals(item.ProductName)
                                && x.QuantityPerUnit == item.QuantityPerUnit
                                && x.ProductID != item.ProductID); //all other products
            if (exist)
                throw new ArgumentException($"{item.ProductName} from " +
                            $"{item.Supplier.CompanyName} of size " +
                            $"{item.QuantityPerUnit} already on file.");

            //after all business rules have been passed, you can assume the 
            //  data is good to be placed on the database



            //there is two steps to complete the process of adding your data to the database
            // a) Staging
            // b) Commit

            //Staging

            EntityEntry<Product> updating = _context.Entry(item);
            updating.State = Microsoft.EntityFrameworkCore.EntityState.Modified;

            //Commit
        
            return _context.SaveChanges(); //if successful, data is committed AND returns rowsaffected count

        }
        #endregion
    }
}
