using Microsoft.EntityFrameworkCore.ChangeTracking;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

#region Additional Namespaces
using WestWindSystem.DAL;
using WestWindSystem.Entities;
#endregion

namespace WestWindSystem.BLL
{
    public class ProductServices
    {
        #region setup of the context connection variable and class constructor
        private readonly WestWindContext _context;

        internal ProductServices(WestWindContext registeredcontext)
        {
            _context = registeredcontext;
        }
        #endregion

        #region Queries
        public List<Product> Product_GetByCategoryID(int categoryid)
        {
            //IEnumerable<Product>info = _context.Products
            //                            .Where(x => x.CategoryID == categoryid);
            //return info.OrderBy(x => x.ProductName).ToList();

            return _context.Products
                           .Where(x => x.CategoryID == categoryid)
                           .OrderBy(x => x.ProductName)
                           .ToList();
        }

        public Product Product_GetByProductID(int productid)
        {
            return _context.Products.FirstOrDefault(x => x.ProductID == productid);
        }
        #endregion

        #region CRUD (Add, Update and Delete)

        public int Product_Add(Product item)
        {

            //Adding a record to your database may require additional validation that was not
            //  done on the front end
            //Such validation could be
            //  was data actually passed to the method
            //  the pkey may not be created on the database, it is user supplied
            //      the pkey value supplied should be tested to see if it already exists
            //  there could be a set of business rules that envolve checking data against
            //      existing data on the database that is not part of the record being added

            //do any validation needed within the service

            //was data passed
            if (item == null) 
                throw new ArgumentNullException("Product information not submitted");

            //does the pkey exist?
            //product has a pkey of IDENTITY
            //there is no need to check to see if the pkey already exists since the
            //      primary key will be generated by the database

            //are there any other business rules to check
            //YOU MAY NOT HAVE ANY OTHER BUSINESS RULES TO CHECK!!!!!!!!!!!!!!!!!!!
            //An example of business rules for this demo could be that the product
            //  a) is not from the same supplier
            //  b) with the same product name
            //  c) having the same quantity per unit
            bool exist = false;
            exist = _context.Products
                        .Any(x => x.SupplierID == item.SupplierID
                                && x.ProductName.Equals(item.ProductName)
                                && x.QuantityPerUnit == item.QuantityPerUnit);
            if (exist)
                throw new ArgumentException($"{item.ProductName} from " +
                            $"{item.Supplier.CompanyName} of size " +
                            $"{item.QuantityPerUnit} already on file.");

            //after all business rules have been passed, you can assume the 
            //  data is good to be placed on the database

            //if your field is an IDENTITY key then override any value in the field 
            //  to zero
            //prevents an IDENTITY_INSERT flag problem from occuring
            item.ProductID = 0;

            //there is two steps to complete the process of adding your data to the database
            // a) Staging
            // b) Commit

            //Staging
            //EntityFramework sets up all db processing in local memory first
            //what is needed for staging
            // a) know the DbSet : Products
            // b) know the action : Add
            // c) know the instance of the DbSet to use: item

            //IMPORTANT: the data is in LOCAL MEMORY
            //           the data is NOT!!! yet been sent to the database
            //THEREFORE: at this time, there is NO!!!!! IDENTITY primary key value
            //              on this instance (except for the default of the datatype)
            //UNLESS: you have place a value in the NON_IDENTITY key field(s)
            _context.Products.Add(item);

            //Commit
            // this sends the ALL staged data in local memory to the database for processing

            //ANY annotation validation in your entity is executed to validate the data
            //  going to the database
            //if there is a validation problem then an exception is thrown and processing of
            //  the commit is terminated (transaction RollBack)
            _context.SaveChanges(); //if successful, data is committed

            //AFTER the successful commit to the database, your new product id
            //  primary key value is available to you via the item.ProductID
            //Optionally, you could return this value to the calling process


            return item.ProductID;
        }

        public int Product_Update(Product item)
        {
            //was data passed
            if (item == null)
                throw new ArgumentNullException("Product information not submitted");

            //does the pkey exist?
            //check via a readonly query that your record target actually exists
            //on the update, this means a simple Any() test
            if(!_context.Products.Any(x => x.ProductID == item.ProductID))
                throw new ArgumentException($"{item.ProductName}  of size " +
                           $"{item.QuantityPerUnit} does not exist on file. Please check for product again.");

            //are there any other business rules to check
            //YOU MAY NOT HAVE ANY OTHER BUSINESS RULES TO CHECK!!!!!!!!!!!!!!!!!!!
            //An example of business rules for this demo could be that the product
            //  a) is not from the same supplier
            //  b) with the same product name
            //  c) having the same quantity per unit
            // AND for update
            //  d) is NOT the current product (all other products)
            bool exist = false;
            exist = _context.Products
                        .Any(x => x.SupplierID == item.SupplierID
                                && x.ProductName.Equals(item.ProductName)
                                && x.QuantityPerUnit == item.QuantityPerUnit
                                && x.ProductID != item.ProductID); //all other products
            if (exist)
                throw new ArgumentException($"{item.ProductName} from " +
                            $"{item.Supplier.CompanyName} of size " +
                            $"{item.QuantityPerUnit} already on file.");

            //after all business rules have been passed, you can assume the 
            //  data is good to be placed on the database



            //there is two steps to complete the process of adding your data to the database
            // a) Staging
            // b) Commit

            //Staging

            EntityEntry<Product> updating = _context.Entry(item);
            updating.State = Microsoft.EntityFrameworkCore.EntityState.Modified;

            //Commit
        
            return _context.SaveChanges(); //if successful, data is committed AND returns rowsaffected count

        }

        //Delete: cruD
        //there are two types of deletes: physical and logical
        //Whether you have a physical or logical delete is determined WHEN
        //  the system is designed (database, data requirements)



        //Logical delete
        //this happens when the record is deemed "unwanted" BUT CANNOT be 
        //  physically removed from the database because the record has
        //  a relationship to another record(s) (parent/child) and the associated record
        //  CANNOT be removed



        //Example: The product record is a parent to ManitfestItems records
        //         The manifest record is need for tracking, it goes to the receiver of the product
        //so, because the other record(s) are required for the business
        //      one CANNOT physically remove the ("parent") product record.



        //usually in this situation, the parent record (product) will have some type of field
        //  that will indicate "deleted"
        //on the product record such a field is the Discontinued field



        //Question: If the record will not be deleted, what happens?
        //Answer: here, you will actually do an update
        //Within the method, it is a good practice NOT to rely on the user to set
        //  the "logical delete" field to the delete status
        //Your method should set the value

        public int Product_LogicalDelete(Product item)
        {
            //was data passed
            if (item == null)
                throw new ArgumentNullException("Product information not submitted");

            //does the pkey exist?
            //the product could have been physically deleted while
            //  the user was doing some processing with the record in question

            //even though this is an update, one technique is to use the existing
            //  data already on the database
            //the only value that needs to be altered is the Discontinued flag
            //if other data was to be altered, then the user should first do the update
            //  then do the discontinue

            //remember, FirstOrDefault will either
            //  a) return the requested record if found
            //  b) return a null

            Product exists = null;
            exists = _context.Products.FirstOrDefault(x => x.ProductID == item.ProductID);
            if (exists == null)
                throw new ArgumentException($"{item.ProductName}  of size " +
                           $"{item.QuantityPerUnit} does not exist on file. Please check for product again.");

            //for the logical delete
            //  set the appropriate field to the value indicating "delete"
            //this code is not relying on the user to have set the appropriate
            //  field on the form
            //  note: no OTHER field on the current record is altered
            exists.Discontinued = true;

            //there is two steps to complete the process of adding your data to the database
            // a) Staging
            // b) Commit

            //Staging

            EntityEntry<Product> updating = _context.Entry(exists);
            updating.State = Microsoft.EntityFrameworkCore.EntityState.Modified;

            //Commit

            return _context.SaveChanges(); //if successful, data is committed AND returns rowsaffected count

        }

        //Physical Delete
        //you physically remove the record from the database
        //IF there are no "child" records to prevent the record removal, you can remove the record
        //IF there are "children" AND the "children" are not required, you can remove the record
        //      HOWEVER, you will need to first remove any "children" before removing the parent record
        //      assuming there is no cascade delete setup on the database

        public int Product_PhysicalDelete(Product item)
        {
            //was data passed
            if (item == null)
                throw new ArgumentNullException("Product information not submitted");

            //does the pkey exist?
            //the product could have been physically deleted while
            //  the user was doing some processing with the record in question

            //check via a readonly query that your record target actually exists
            //on the update, this means a simple Any() test

            if (!_context.Products.Any(x => x.ProductID == item.ProductID))
                throw new ArgumentException($"{item.ProductName}  of size " +
                           $"{item.QuantityPerUnit} does not exist on file. Please check for product again.");


            //this delete assumes that there is no appropriate field on the 
            //  record to indicate a logical "delete" and thus: a physical
            //  delete will occur

            //HOWEVER!! this record could be a parent to one or more "child" records
            //One should ensure that there is no existing child record for the
            //  parent BEFORE attempting the delete

            //using the virtual navigational properties, one could check to see
            //  if any child records (collection) exists for the parent
            //if there is a cascade delete setup on your dataset and is allowed
            //  then these checks are unnecessary

            if (_context.Products.Any(x => x.ManifestItems.Count > 0))
                throw new ArgumentException($"{item.ProductName}  of size " +
                        $"{item.QuantityPerUnit} has associated manifest item records. Unable to remove product.");

            if (_context.Products.Any(x => x.OrderDetails.Count > 0))
                throw new ArgumentException($"{item.ProductName}  of size " +
                        $"{item.QuantityPerUnit} has associated order detail records. Unable to remove product.");

            //after all business rules have been passed, you can assume the 
            //  data is good to be processed on the database

            //there is two steps to complete the process of adding your data to the database
            // a) Staging
            // b) Commit

            //Staging

            EntityEntry<Product> deleting = _context.Entry(item);
            deleting.State = Microsoft.EntityFrameworkCore.EntityState.Deleted;

            //Commit

            return _context.SaveChanges(); //if successful, data is committed AND returns rowsaffected count

        }
        #endregion

    }
}
