// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RenoSystem.ENTITIES;

public partial class Client
{
    [Key]
    public int ClientId { get; set; }

    [Required]
    [StringLength(50)]
    public string Contact { get; set; }

    [Required]
    [StringLength(10)]
    public string Phone { get; set; }

    [Required]
    [StringLength(8)]
    public string Number { get; set; }

    [StringLength(5)]
    public string Unit { get; set; }

    [Required]
    [StringLength(25)]
    public string Street { get; set; }

    [Required]
    [StringLength(25)]
    public string City { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string Province { get; set; }

    [Required]
    [StringLength(6)]
    [Unicode(false)]
    public string PostalCode { get; set; }

    [InverseProperty("Client")]
    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
}