// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RenoSystem.ENTITIES;

public partial class Job
{
    [Key]
    public int JobId { get; set; }

    public int ClientId { get; set; }

    [Required]
    [StringLength(500)]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CompletionDate { get; set; }

    [Required]
    [StringLength(12)]
    public string PlanId { get; set; }

    [ForeignKey("ClientId")]
    [InverseProperty("Jobs")]
    public virtual Client Client { get; set; }

    [InverseProperty("Job")]
    public virtual ICollection<Labour> Labours { get; set; } = new List<Labour>();

    [InverseProperty("Job")]
    public virtual ICollection<Supply> Supplies { get; set; } = new List<Supply>();
}