// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RenoSystem.ENTITIES;

public partial class Labour
{
    [Key]
    public int LabourId { get; set; }

    public int JobId { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    public double Hours { get; set; }

    [Column(TypeName = "money")]
    public decimal LabourCost { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ScheduleDate { get; set; }

    [ForeignKey("JobId")]
    [InverseProperty("Labours")]
    public virtual Job Job { get; set; }
}