// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RenoSystem.ENTITIES;

public partial class Supply
{
    [Key]
    public int SupplyId { get; set; }

    public int JobId { get; set; }

    [Required]
    [StringLength(100)]
    public string Material { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "money")]
    public decimal MaterialCost { get; set; }

    [ForeignKey("JobId")]
    [InverseProperty("Supplies")]
    public virtual Job Job { get; set; }
}